pygments: true
auto: true
permalink: /blog/:year-:month-:day/:title
exclude:
- README.markdown

markdown: rdiscount
rdiscount:
    extensions: [smart]

#--- site vars
author: Johnson Page
url: http://johnsonpage.org
email: jwpage+site@gmail.com
local: true
