pygments: true
auto: true
permalink: /blog/:year-:month-:day/:title
exclude:
- Rakefile
- README.markdown
#--- site vars
author: Johnson Page
url: http://johnsonpage.org
email: jwpage+site@gmail.com
local: true
